// Generated by shared/schema/generate-settings.mjs. Do not edit.

export interface SettingsData {
  color_theme: "tailsync" | "ocean" | "forest" | "rose" | "high-contrast";
  connection_mode: "auto" | "lan_only" | "tailscale_only";
  enabled_peers: Record<string, boolean>;
  history_limit: number;
  language: "en" | "zh-CN";
  notifications_enabled: boolean;
  paired_peer_endpoints: Record<string, string>;
  progress_bar_enabled: boolean;
  theme: "system" | "light" | "dark";
  trusted_peer_addresses: Record<string, Record<string, string>>;
  trusted_peer_keys: Record<string, string>;
}
