use super::*;

pub(super) fn builtin_ids() -> [&'static str; 5] {
    [CANVAS_ID, FLUX_ID, LEDGER_ID, AURA_ID, MONO_ID]
}

pub(super) fn builtin_name(id: &str) -> &'static str {
    match id {
        CANVAS_ID => "Canvas",
        FLUX_ID => "Flux",
        LEDGER_ID => "Ledger",
        AURA_ID => "Aura",
        MONO_ID => "Mono",
        _ => "Canvas",
    }
}

pub(super) fn component_state(
    background: &str,
    foreground: &str,
    secondary_text: &str,
    accent: &str,
) -> Value {
    serde_json::json!({
        "background": background,
        "foreground": foreground,
        "secondaryText": secondary_text,
        "border": "ref:/colors/border/default",
        "focusRing": accent,
        "icon": secondary_text,
        "accent": accent,
        "radius": 9,
        "padding": 10,
        "spacing": 8,
        "typography": {"size": 13, "weight": 400},
        "shadow": {"radius": 8, "y": 3, "opacity": 0.10}
    })
}

pub(super) fn component_defaults() -> Value {
    let mut components = serde_json::Map::new();
    for component in COMPONENT_NAMES {
        let mut states = serde_json::Map::new();
        states.insert(
            "default".into(),
            component_state(
                if *component == "search" || *component == "input" {
                    "ref:/colors/background/input"
                } else {
                    "ref:/colors/background/surface"
                },
                "ref:/colors/text/primary",
                "ref:/colors/text/secondary",
                "ref:/colors/accent/default",
            ),
        );
        states.insert(
            "hover".into(),
            component_state(
                "ref:/colors/background/hover",
                "ref:/colors/text/primary",
                "ref:/colors/text/secondary",
                "ref:/colors/accent/hover",
            ),
        );
        states.insert(
            "active".into(),
            component_state(
                "ref:/colors/background/active",
                "ref:/colors/text/primary",
                "ref:/colors/text/secondary",
                "ref:/colors/accent/default",
            ),
        );
        states.insert(
            "selected".into(),
            component_state(
                "ref:/colors/accent/soft",
                "ref:/colors/text/primary",
                "ref:/colors/text/secondary",
                "ref:/colors/accent/default",
            ),
        );
        states.insert(
            "disabled".into(),
            component_state(
                "ref:/colors/background/surface",
                "ref:/colors/text/tertiary",
                "ref:/colors/text/tertiary",
                "ref:/colors/text/tertiary",
            ),
        );
        states.insert(
            "focus".into(),
            component_state(
                if *component == "search" || *component == "input" {
                    "ref:/colors/background/input"
                } else {
                    "ref:/colors/background/surface"
                },
                "ref:/colors/text/primary",
                "ref:/colors/text/secondary",
                "ref:/colors/accent/default",
            ),
        );
        components.insert((*component).into(), Value::Object(states));
    }
    Value::Object(components)
}

/// The built-ins are Core data, not renderer CSS.  Keep this table in lockstep
/// with the original five palettes so every client resolves the same 24 colors.
pub(super) fn builtin_tokens(id: &str, mode: &str) -> Value {
    let dark = mode == "dark";
    let (
        accent,
        hover,
        soft,
        on,
        bg,
        surface,
        input,
        bg_hover,
        active,
        raised,
        toast,
        primary,
        secondary,
        tertiary,
        text_toast,
        border,
        strong,
        divider,
        positive,
        positive_soft,
        warning,
        warning_soft,
        info,
        info_soft,
    ) = match (id, dark) {
        (CANVAS_ID, false) => (
            "#d5684b",
            "#bb553b",
            "rgba(213, 104, 75, 0.11)",
            "#ffffff",
            "#faf9f5",
            "#fffefa",
            "rgba(26, 25, 22, 0.045)",
            "#f0eee7",
            "#e8e4da",
            "#fffefa",
            "#171716",
            "#191918",
            "#68665f",
            "#98958b",
            "#ffffff",
            "#e7e3d9",
            "#d3cec2",
            "#ece8df",
            "#44745a",
            "rgba(68, 116, 90, 0.11)",
            "#b96536",
            "rgba(185, 101, 54, 0.11)",
            "#765b8f",
            "rgba(118, 91, 143, 0.11)",
        ),
        (CANVAS_ID, true) => (
            "#ec8668",
            "#f29b80",
            "rgba(236, 134, 104, 0.14)",
            "#181412",
            "#191918",
            "#232321",
            "rgba(255, 253, 245, 0.055)",
            "#292825",
            "#33312d",
            "#262522",
            "#f8f5ed",
            "#f4f1e9",
            "#aaa69c",
            "#77746c",
            "#171716",
            "#32312d",
            "#48463f",
            "#2c2b28",
            "#75aa86",
            "rgba(117, 170, 134, 0.14)",
            "#dc9163",
            "rgba(220, 145, 99, 0.14)",
            "#ad8cc6",
            "rgba(173, 140, 198, 0.14)",
        ),
        (FLUX_ID, false) => (
            "#147970",
            "#0e635d",
            "rgba(20, 121, 112, 0.1)",
            "#ffffff",
            "#f4f8f6",
            "#fbfdfb",
            "rgba(10, 57, 54, 0.045)",
            "#e8f0ed",
            "#dbe8e3",
            "#ffffff",
            "#0e2422",
            "#102724",
            "#58706c",
            "#879a96",
            "#ffffff",
            "#dce8e4",
            "#bfd2cd",
            "#e3ece9",
            "#147970",
            "rgba(20, 121, 112, 0.1)",
            "#b96536",
            "rgba(185, 101, 54, 0.11)",
            "#765b8f",
            "rgba(118, 91, 143, 0.11)",
        ),
        (FLUX_ID, true) => (
            "#65c8bd",
            "#7bd7ce",
            "rgba(101, 200, 189, 0.13)",
            "#09201e",
            "#111b1a",
            "#182422",
            "rgba(226, 255, 250, 0.055)",
            "#21302e",
            "#293b38",
            "#1c2927",
            "#ecfaf7",
            "#eaf7f4",
            "#9cb7b2",
            "#6d8984",
            "#0b1816",
            "#263633",
            "#3c5450",
            "#21302e",
            "#65c8bd",
            "rgba(101, 200, 189, 0.13)",
            "#dc9163",
            "rgba(220, 145, 99, 0.14)",
            "#ad8cc6",
            "rgba(173, 140, 198, 0.14)",
        ),
        (LEDGER_ID, false) => (
            "#536859",
            "#405246",
            "rgba(83, 104, 89, 0.1)",
            "#ffffff",
            "#f7f7f3",
            "#fdfdf9",
            "rgba(38, 48, 40, 0.045)",
            "#eceee8",
            "#e0e4dc",
            "#fffffb",
            "#1b211c",
            "#202720",
            "#626b63",
            "#929a92",
            "#ffffff",
            "#e0e4dc",
            "#c8d0c7",
            "#e7e9e3",
            "#536859",
            "rgba(83, 104, 89, 0.1)",
            "#b96536",
            "rgba(185, 101, 54, 0.11)",
            "#765b8f",
            "rgba(118, 91, 143, 0.11)",
        ),
        (LEDGER_ID, true) => (
            "#93b09c",
            "#a8c1af",
            "rgba(147, 176, 156, 0.13)",
            "#121814",
            "#161a16",
            "#202520",
            "rgba(241, 252, 243, 0.05)",
            "#282e28",
            "#323a33",
            "#242a24",
            "#f2f6f1",
            "#edf2ec",
            "#a7b2a7",
            "#737d74",
            "#151a16",
            "#2d352e",
            "#465047",
            "#282f29",
            "#93b09c",
            "rgba(147, 176, 156, 0.13)",
            "#dc9163",
            "rgba(220, 145, 99, 0.14)",
            "#ad8cc6",
            "rgba(173, 140, 198, 0.14)",
        ),
        (AURA_ID, false) => (
            "#a34f75",
            "#893e61",
            "rgba(163, 79, 117, 0.1)",
            "#ffffff",
            "#faf7f9",
            "#fffdfd",
            "rgba(70, 34, 55, 0.045)",
            "#f2e9ee",
            "#eadce3",
            "#ffffff",
            "#2c1c25",
            "#2d2229",
            "#76636e",
            "#a18f99",
            "#ffffff",
            "#eadde4",
            "#d5c1cc",
            "#f0e5ea",
            "#536859",
            "rgba(83, 104, 89, 0.1)",
            "#a34f75",
            "rgba(163, 79, 117, 0.1)",
            "#a34f75",
            "rgba(163, 79, 117, 0.1)",
        ),
        (AURA_ID, true) => (
            "#dc8daf",
            "#e6a3bf",
            "rgba(220, 141, 175, 0.13)",
            "#26151d",
            "#1d171b",
            "#281f24",
            "rgba(255, 239, 247, 0.055)",
            "#33272d",
            "#3f3038",
            "#2d2328",
            "#fff5f9",
            "#faeef4",
            "#c0a6b2",
            "#866f7a",
            "#20151a",
            "#382c32",
            "#58434d",
            "#30252a",
            "#93b09c",
            "rgba(147, 176, 156, 0.13)",
            "#dc8daf",
            "rgba(220, 141, 175, 0.13)",
            "#dc8daf",
            "rgba(220, 141, 175, 0.13)",
        ),
        (MONO_ID, false) => (
            "#111111",
            "#000000",
            "rgba(0, 0, 0, 0.08)",
            "#ffffff",
            "#ffffff",
            "#ffffff",
            "#f3f3f3",
            "#eeeeee",
            "#dfdfdf",
            "#ffffff",
            "#000000",
            "#080808",
            "#454545",
            "#6d6d6d",
            "#ffffff",
            "#d5d5d5",
            "#8c8c8c",
            "#dedede",
            "#111111",
            "rgba(0, 0, 0, 0.08)",
            "#3d3d3d",
            "rgba(0, 0, 0, 0.08)",
            "#656565",
            "rgba(0, 0, 0, 0.08)",
        ),
        (MONO_ID, true) => (
            "#f5f5f5",
            "#ffffff",
            "rgba(255, 255, 255, 0.12)",
            "#080808",
            "#080808",
            "#101010",
            "#181818",
            "#1d1d1d",
            "#292929",
            "#121212",
            "#ffffff",
            "#ffffff",
            "#c8c8c8",
            "#8e8e8e",
            "#000000",
            "#2c2c2c",
            "#747474",
            "#252525",
            "#f5f5f5",
            "rgba(255, 255, 255, 0.12)",
            "#c8c8c8",
            "rgba(255, 255, 255, 0.1)",
            "#969696",
            "rgba(255, 255, 255, 0.08)",
        ),
        _ => return builtin_tokens(CANVAS_ID, mode),
    };
    let display = match id {
        CANVAS_ID | LEDGER_ID => vec![
            "STZhongsong",
            "Songti SC",
            "STSong",
            "SimSun",
            "Iowan Old Style",
            "Baskerville",
            "Georgia",
            "serif",
        ],
        FLUX_ID => vec![
            "Bahnschrift",
            "DengXian",
            "Avenir Next",
            "Hiragino Sans GB",
            "Segoe UI Variable Display",
            "sans-serif",
        ],
        AURA_ID => vec![
            "Candara",
            "YouYuan",
            "Hiragino Maru Gothic ProN",
            "PingFang SC",
            "Microsoft YaHei UI",
            "sans-serif",
        ],
        MONO_ID => vec![
            "Cascadia Mono",
            "Cascadia Code",
            "SF Mono",
            "IBM Plex Mono",
            "monospace",
        ],
        _ => vec!["system-ui"],
    };
    serde_json::json!({"colors":{"accent":{"default":accent,"hover":hover,"soft":soft,"onAccent":on},"background":{"canvas":bg,"surface":surface,"input":input,"hover":bg_hover,"active":active,"raised":raised,"toast":toast},"text":{"primary":primary,"secondary":secondary,"tertiary":tertiary,"toast":text_toast},"border":{"default":border,"strong":strong,"divider":divider},"status":{"positive":positive,"positiveSoft":positive_soft,"warning":warning,"warningSoft":warning_soft,"info":info,"infoSoft":info_soft}},"typography":{"ui":{"families":["Segoe UI Variable Text","Segoe UI","Microsoft YaHei UI","PingFang SC","sans-serif"],"size":13,"lineHeight":20,"weight":400},"display":{"families":display},"reading":{"families":["Segoe UI Variable Text","Segoe UI","Microsoft YaHei UI","PingFang SC","sans-serif"]},"search":{"size":if id == FLUX_ID || id == MONO_ID {16}else{18},"useDisplayFont":!(id == FLUX_ID || id == MONO_ID)},"section":{"size":if id == MONO_ID {18}else{23},"uppercase":id == FLUX_ID || id == MONO_ID},"history":{"size":13}},"density":{"control":13,"row":13},"shape":{"controlRadius":if id == MONO_ID {3}else{9},"surfaceRadius":if id == MONO_ID {3}else{10},"windowRadius":if id == MONO_ID {3}else{10}},"effects":{"opacity":1,"shadow":{"radius":if id == MONO_ID {0}else{70},"y":if id == MONO_ID {0}else{24},"opacity":if id == MONO_ID {0.0}else{0.16}},"motion":{"fast":160,"slow":420,"easing":"cubic-bezier(0.22, 1, 0.36, 1)"}},"components":component_defaults()})
}
